### Analisis de rendimiento - Fútbol Femenino

El equipo de fútbol femenino "Estrellas FC" quiere evaluar el rendimiento de sus jugadoras a lo largo de la última temporada para planificar entrenamientos, formaciones y estrategias para los próximos partidos. Como parte del equipo de análisis de datos del club, tu tarea es analizar el conjunto de datos de las asistencias utilizando Python y Numpy.

Objetivos:

- Analizar la contribución de cada jugadora al equipo.
- Identificar las jugadoras con mejor y peor rendimiento.
- Evaluar la consistencia del rendimiento de las jugadoras a lo largo de la temporada.
- Desarrollar recomendaciones para el entrenamiento y la formación basadas en los resultados.

In [1]:
# Importa las librerías necesaria para el desarrollo de nuestro ejercicio.

import numpy as np

In [3]:
# Crea un array bidimensional 'asistencias' para las 11 jugadoras titulares a lo largo de 30 partidos.

rendimiento = np.random.randint(0, 10, size=(30, 11))

print(rendimiento)

[[9 7 0 5 4 5 5 8 3 2 2]
 [9 2 1 7 2 4 2 7 6 2 9]
 [1 5 3 2 2 0 2 4 3 9 1]
 [9 3 4 3 7 9 3 3 9 7 1]
 [5 4 3 0 4 0 7 6 1 5 6]
 [7 8 4 8 3 2 3 2 4 7 7]
 [6 8 1 9 1 0 0 7 3 3 1]
 [7 9 3 9 9 9 6 8 2 1 6]
 [8 6 7 4 9 8 4 1 7 8 4]
 [8 2 3 8 1 9 7 1 0 9 2]
 [2 6 0 6 4 7 0 3 5 2 1]
 [0 5 4 7 6 4 1 6 4 9 4]
 [2 5 2 8 5 8 1 9 0 3 2]
 [0 7 3 4 9 6 4 9 2 1 5]
 [4 7 3 5 1 5 7 4 3 6 6]
 [1 0 1 9 5 3 7 4 5 7 7]
 [6 0 9 3 9 8 9 0 9 3 5]
 [9 5 0 8 1 2 7 0 3 9 2]
 [8 8 9 2 4 6 7 8 8 9 3]
 [5 5 6 8 7 4 1 7 3 0 0]
 [0 4 3 4 6 2 1 5 2 5 6]
 [0 3 7 2 7 8 2 9 1 0 9]
 [0 9 0 0 1 3 8 5 3 5 7]
 [0 3 4 3 7 4 4 5 9 3 7]
 [1 8 8 8 6 2 5 9 0 6 2]
 [4 3 1 7 7 3 9 4 9 9 1]
 [3 1 8 0 7 4 0 5 7 7 7]
 [3 3 1 8 3 0 1 6 7 8 1]
 [3 8 2 5 1 0 7 5 6 6 0]
 [9 5 0 2 7 5 5 7 1 5 7]]


In [4]:
# Calcula el total de asistencias por jugadora a lo largo de la temporada.

total_asistencias = rendimiento.sum(axis=0)

print(total_asistencias)

[129 149 100 154 145 130 125 157 125 156 121]


In [8]:
# Corrige los datos en el partido número 20, aumenta la cantidad de asistencias de la jugadora 5 en 2.

print(rendimiento[19, 4])

rendimiento[19, 4] += 2

print(rendimiento[19, 4])

9
11


In [9]:
# Calcula el promedio de asistencia por jugadora a lo largo de la temporada.

prom_asistencias = rendimiento.mean(axis=0)

print(prom_asistencias)

[4.3        4.96666667 3.33333333 5.13333333 4.96666667 4.33333333
 4.16666667 5.23333333 4.16666667 5.2        4.03333333]


In [10]:
# Selecciona y muestra las asistencias de las jugadoras en el final de la temporada (los últimos 10 partidos).

ultimo_rendimiento = rendimiento[-10:, :]

print(ultimo_rendimiento)

[[0 4 3 4 6 2 1 5 2 5 6]
 [0 3 7 2 7 8 2 9 1 0 9]
 [0 9 0 0 1 3 8 5 3 5 7]
 [0 3 4 3 7 4 4 5 9 3 7]
 [1 8 8 8 6 2 5 9 0 6 2]
 [4 3 1 7 7 3 9 4 9 9 1]
 [3 1 8 0 7 4 0 5 7 7 7]
 [3 3 1 8 3 0 1 6 7 8 1]
 [3 8 2 5 1 0 7 5 6 6 0]
 [9 5 0 2 7 5 5 7 1 5 7]]


In [11]:
# Calcula las asistencias del final de la temporada y comparalo vs las asistencias del inicio. ¿Fue mejor?

inicio_rendimiento = rendimiento[10:, :]

asistencias_inicio = inicio_rendimiento.sum(axis=0)
asistencias_final = ultimo_rendimiento.sum(axis=0)

print(asistencias_inicio)
print(asistencias_final)

[ 60  95  71  99 107  84  86 110  87 103  82]
[23 47 34 39 52 31 42 60 45 54 47]


In [12]:
total_asistencias_inicio=np.sum(asistencias_inicio)
total_asistencias_final=np.sum(asistencias_final)

if total_asistencias_inicio > total_asistencias_final:
    print("El comienzo de temporada fue mejor al final.")
elif total_asistencias_inicio < total_asistencias_final:
    print("El final de temporada fue mejor al inicio.")
else:
    print("El nivel se rendimiento se mantuvo tanto al inicio como al final de la temporada.")

El comienzo de temporada fue mejor al final.


In [13]:
# Crea una máscara que identificar partidos en los que cualquier jugadora superó las 5 asistencias.

mascara_asistencias = rendimiento > 5

print(mascara_asistencias)

[[ True  True False False False False False  True False False False]
 [ True False False  True False False False  True  True False  True]
 [False False False False False False False False False  True False]
 [ True False False False  True  True False False  True  True False]
 [False False False False False False  True  True False False  True]
 [ True  True False  True False False False False False  True  True]
 [ True  True False  True False False False  True False False False]
 [ True  True False  True  True  True  True  True False False  True]
 [ True  True  True False  True  True False False  True  True False]
 [ True False False  True False  True  True False False  True False]
 [False  True False  True False  True False False False False False]
 [False False False  True  True False False  True False  True False]
 [False False False  True False  True False  True False False False]
 [False  True False False  True  True False  True False False False]
 [False  True False False False Fa

In [14]:
# Filtra  el valor de esas asistencias en cada partido.

partidos_importantes = rendimiento[mascara_asistencias]
print(partidos_importantes)

[ 9  7  8  9  7  7  6  9  9  9  7  9  9  7  7  6  6  7  8  8  7  7  6  8
  9  7  7  9  9  9  9  6  8  6  8  6  7  9  8  7  8  8  8  9  7  9  6  6
  7  7  6  6  9  8  8  9  7  9  6  9  7  7  6  6  9  7  7  7  6  9  9  8
  9  9  9  8  7  9  8  8  9  6  7  8  8  9  6  8 11  7  6  6  7  7  8  9
  9  9  8  7  7  9  7  8  8  8  6  9  6  7  7  9  9  9  8  7  7  7  7  8
  6  7  8  8  7  6  6  9  7  7  7]


In [16]:
# Calcula la varianza y la desviación estándar de las asistencias por jugadora

varianza_recuperaciones = np.var(rendimiento, axis=0)
desviacion_std_recuperaciones = np.std(rendimiento, axis=0)

print(varianza_recuperaciones)
print(desviacion_std_recuperaciones)

[11.07666667  6.56555556  7.68888889  8.31555556  8.43222222  8.48888889
  8.07222222  7.04555556  8.20555556  8.56        7.63222222]
[3.32816266 2.56233401 2.77288458 2.8836705  2.90382889 2.91356978
 2.84116564 2.65434654 2.86453409 2.92574777 2.76264768]
